# Generated by Django 3.2 on 2022-02-10 12:50

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('brand', models.CharField(max_length=10, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='core.brand')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('new', models.BooleanField(default=True, verbose_name='Novo')),
                ('kms', models.PositiveIntegerField(default=0, verbose_name='Kms Rodados')),
                ('year', models.CharField(choices=[('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], default='2022', max_length=4, verbose_name='Ano')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('color', models.CharField(choices=[('Amarelo', 'Amarelo'), ('Azul', 'Azul'), ('Branco', 'Branco'), ('Preto', 'Preto'), ('Vermelho', 'Vermelho'), ('Cinza', 'Cinza'), ('Bege', 'Bege'), ('Vinho', 'Vinho'), ('Verde', 'Verde'), ('Marrom', 'Marrom')], default='Branco', max_length=9, verbose_name='Cor')),
                ('category', models.CharField(choices=[('Hatch', 'Hatch'), ('Minivan', 'Minivan'), ('Perua', 'Perua'), ('Picape', 'Picape'), ('Picape C. Dupla', 'Picape C. Dupla'), ('SUV', 'SUV'), ('Seda', 'Sedã')], default='Hatch', max_length=15, verbose_name='Categoria')),
                ('exchange', models.CharField(choices=[('Semi-automatico', 'Semi-automático'), ('Automatico', 'Automático'), ('CVT', 'CVT'), ('Manual', 'Manual')], default='Manual', max_length=15, verbose_name='Câmbio')),
                ('fuel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('A/G', 'Á/G'), ('Alcool', 'Álcool')], default='Gasolina', max_length=10, verbose_name='Combustível')),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, verbose_name='Portas')),
                ('image', stdimage.models.StdImageField(upload_to='carros', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='core.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='core.carmodel')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
