# Generated by Django 3.2 on 2022-02-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car',
            field=models.CharField(default='Gol 1.0', editable=False, max_length=100, verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='car',
            name='exchange',
            field=models.CharField(choices=[('Semi-automatico', 'Semi-automático'), ('Manual', 'Manual'), ('CVT', 'CVT'), ('Automatico', 'Automático')], default='Manual', max_length=15, verbose_name='Câmbio'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='core.brand'),
        ),
    ]
