# Generated by Django 3.2 on 2022-02-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220210_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='exchange',
            field=models.CharField(choices=[('Semi-automatico', 'Semi-automático'), ('CVT', 'CVT'), ('Manual', 'Manual'), ('Automatico', 'Automático')], default='Manual', max_length=15, verbose_name='Câmbio'),
        ),
    ]
