# Generated by Django 3.2 on 2022-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220214_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='exchange',
            field=models.CharField(choices=[('Automatico', 'Automático'), ('Semi-automatico', 'Semi-automático'), ('CVT', 'CVT'), ('Manual', 'Manual')], default='Manual', max_length=15, verbose_name='Câmbio'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(choices=[('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], default=2022, verbose_name='Ano'),
        ),
    ]
